/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.DanhGia_DAO;
import java.util.List;
import javax.swing.Icon;

/**
 *
 * @author hoang
 */
public class ChiTietDanhGiaJPanel extends javax.swing.JPanel {

    DanhGia_DAO dg_DAO = new DanhGia_DAO();
    
    /**
     * Creates new form ChiTietDanhGia
     */
    public ChiTietDanhGiaJPanel() {
        initComponents();
        loadDanhGia(7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void loadDanhGia(int mahd){
        List<Object[]> list = dg_DAO.loadDanhGia(mahd);
        for (Object[] danhGia : list) {
            String tenMon = (String) danhGia[0];
            System.out.println(tenMon);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblHinhAnh = new javax.swing.JLabel();
        chk1Sao = new javax.swing.JCheckBox();
        chk2Sao = new javax.swing.JCheckBox();
        chk3Sao = new javax.swing.JCheckBox();
        chk4Sao = new javax.swing.JCheckBox();
        chk5Sao = new javax.swing.JCheckBox();
        lblTenMon = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 150));

        lblHinhAnh.setText("Hình Ảnh");

        buttonGroup1.add(chk1Sao);
        chk1Sao.setText("1 Sao");

        buttonGroup1.add(chk2Sao);
        chk2Sao.setText("2 Sao");

        buttonGroup1.add(chk3Sao);
        chk3Sao.setText("3 Sao");

        buttonGroup1.add(chk4Sao);
        chk4Sao.setText("4 Sao");

        buttonGroup1.add(chk5Sao);
        chk5Sao.setText("5 Sao");

        lblTenMon.setText("Tên Món Ăn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk1Sao)
                        .addGap(18, 18, 18)
                        .addComponent(chk2Sao)
                        .addGap(18, 18, 18)
                        .addComponent(chk3Sao)
                        .addGap(18, 18, 18)
                        .addComponent(chk4Sao)
                        .addGap(18, 18, 18)
                        .addComponent(chk5Sao))
                    .addComponent(lblTenMon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTenMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk1Sao)
                    .addComponent(chk2Sao)
                    .addComponent(chk3Sao)
                    .addComponent(chk4Sao)
                    .addComponent(chk5Sao))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk1Sao;
    private javax.swing.JCheckBox chk2Sao;
    private javax.swing.JCheckBox chk3Sao;
    private javax.swing.JCheckBox chk4Sao;
    private javax.swing.JCheckBox chk5Sao;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblTenMon;
    // End of variables declaration//GEN-END:variables
}
