/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.ChuyenManHinh;
import Controller.DatBanDao;
import Controller.PhieuDatBanDao;
import Utils.MsgBox;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Võ Thanh Tùng
 */
public class JDiaLogDangPhucVu extends javax.swing.JDialog {

    DatBanDao dbDAO = new DatBanDao();
    List<Integer> maBan = new ArrayList<>();

    /**
     * Creates new form JDiaLogDangPhucVu
     */
    public JDiaLogDangPhucVu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public void setBan(List<Integer> maBanList) {
        maBan = maBanList;
        if (!maBanList.isEmpty()) {
            String maBanText = "Bàn: ";
            for (Integer maBan : maBanList) {
                maBanText += maBan + " ";
            }
            lbMaBan.setText(maBanText);
        } else {

        }
//        layMaBan(maBan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMaBan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbThemMon = new javax.swing.JLabel();
        lbThanhToans = new javax.swing.JLabel();
        lbChuyenBan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbMaBan.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbMaBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaBan.setText("Ban: 1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Trạng thái: Đang Phục vụ");

        lbThemMon.setBackground(new java.awt.Color(51, 255, 0));
        lbThemMon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbThemMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/da dat.png"))); // NOI18N
        lbThemMon.setText("Thêm món");
        lbThemMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbThemMon.setFocusTraversalPolicyProvider(true);
        lbThemMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemMonMouseClicked(evt);
            }
        });

        lbThanhToans.setBackground(new java.awt.Color(51, 255, 0));
        lbThanhToans.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbThanhToans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bao tri.png"))); // NOI18N
        lbThanhToans.setText("Thanh Toán");
        lbThanhToans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbThanhToans.setFocusTraversalPolicyProvider(true);
        lbThanhToans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThanhToansMouseClicked(evt);
            }
        });

        lbChuyenBan.setBackground(new java.awt.Color(51, 255, 0));
        lbChuyenBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbChuyenBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ChuyenBan.png"))); // NOI18N
        lbChuyenBan.setText("Chuyển bàn");
        lbChuyenBan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbChuyenBan.setFocusTraversalPolicyProvider(true);
        lbChuyenBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbChuyenBanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbThemMon))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbThanhToans))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbChuyenBan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbThemMon)
                .addGap(18, 18, 18)
                .addComponent(lbThanhToans)
                .addGap(18, 18, 18)
                .addComponent(lbChuyenBan)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbThemMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemMonMouseClicked
        int maBann = maBan.get(0);
        this.setVisible(false);
        PhieuDatBanDao pdb = new PhieuDatBanDao();
        int MaPDB = pdb.SelectMaPDB(maBann);
        boolean foundButton = false;
        JButton button;
        button = JPanelTang1.timButtonByMaBan(maBann);
        if (button != null) {
            button.setToolTipText(MaPDB + "");
            MaPDB = Integer.parseInt(button.getToolTipText());
            foundButton = true;
        }

        if (!foundButton) {
            button = JPanelTang2.timButtonByMaBan(maBann);
            if (button != null) {
                button.setToolTipText(MaPDB + "");
                MaPDB = Integer.parseInt(button.getToolTipText());
                foundButton = true;
            }
        }

        if (!foundButton) {
            button = JPanelTang3.timButtonByMaBan(maBann);
            if (button != null) {
                button.setToolTipText(MaPDB + "");
                MaPDB = Integer.parseInt(button.getToolTipText());
            }
        }

        GoiMon dialogGoiMon = new GoiMon();
        JDialog dialog = new JDialog();
        dialog.getContentPane().add(dialogGoiMon);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
//        dialogGoiMon.filltableCoSan(MaPDB);
        dialogGoiMon.setKHvaTG(MaPDB);
        dialogGoiMon.filltableCoSan(MaPDB);
    }//GEN-LAST:event_lbThemMonMouseClicked

    private void lbThanhToansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThanhToansMouseClicked
        int maBann = maBan.get(0);
        this.setVisible(false);
        PhieuDatBanDao pdb = new PhieuDatBanDao();
        int MaPDB = pdb.SelectMaPDB(maBann);
        boolean foundButton = false;
        JButton button;
        button = JPanelTang1.timButtonByMaBan(maBann);
        if (button != null) {
            button.setToolTipText(MaPDB + "");
            MaPDB = Integer.parseInt(button.getToolTipText());
            foundButton = true;
        }

        if (!foundButton) {
            button = JPanelTang2.timButtonByMaBan(maBann);
            if (button != null) {
                button.setToolTipText(MaPDB + "");
                MaPDB = Integer.parseInt(button.getToolTipText());
                foundButton = true;
            }
        }

        if (!foundButton) {
            button = JPanelTang3.timButtonByMaBan(maBann);
            if (button != null) {
                button.setToolTipText(MaPDB + "");
                MaPDB = Integer.parseInt(button.getToolTipText());
            }
        }

        GoiMon dialogGoiMon = new GoiMon();
        JDialog dialog = new JDialog();
        dialog.getContentPane().add(dialogGoiMon);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialogGoiMon.setKHvaTG(MaPDB);
        dialogGoiMon.filltableCoSan(MaPDB);
        ActionEvent actionEvent = new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "MouseClicked");
        dialogGoiMon.jButton2ActionPerformed(actionEvent);
    }//GEN-LAST:event_lbThanhToansMouseClicked

    private void lbChuyenBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbChuyenBanMouseClicked
          
        JFrame fr = new JFrame();
        JDiaLOgChuyenBan dialog = new JDiaLOgChuyenBan(fr,true);
        dialog.setBan(maBan);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_lbChuyenBanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDiaLogDangPhucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDiaLogDangPhucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDiaLogDangPhucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDiaLogDangPhucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDiaLogDangPhucVu dialog = new JDiaLogDangPhucVu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbChuyenBan;
    private javax.swing.JLabel lbMaBan;
    private javax.swing.JLabel lbThanhToans;
    private javax.swing.JLabel lbThemMon;
    // End of variables declaration//GEN-END:variables
     public void thayDoiTrangThai(String maBan) {
        dbDAO.updateTrangThai(DatBanDao.Trong, maBan);
    }
}
