/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author buimi
 */
import Controller.ThucDonDAO;
import Model.MonAn;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ThucDon extends javax.swing.JPanel {

    /**
     * Creates new form ThucDon1
     */
    private ThucDonDAO thucDonDAO;

    public ThucDon() {
        initComponents();
        thucDonDAO = new ThucDonDAO();
        loadDanhSachMonAn();
        initCombobox();
    }

    private void loadDanhSachMonAn() {
        List<MonAn> danhSachMonAn = thucDonDAO.layDanhSachThucDon();
        loadDanhSachMonLenTable(danhSachMonAn);
    }

    public void loadDanhSachMonLenTable(List<MonAn> danhSachMonAn) {
        DefaultTableModel model = (DefaultTableModel) tblThucDon.getModel();
        model.setRowCount(0);
        String ngayPhucVu;

        for (MonAn monAn : danhSachMonAn) {
            String maThucDon = monAn.getNgayPhucVu();

            if ("1".equals(maThucDon)) {
                ngayPhucVu = "Thứ 2,4,6,CN";
            } else {
                ngayPhucVu = "Thứ 3,5,7";
            }

            Object[] rowData = {monAn.getTenMonAn(), monAn.getLoaiMonAn(), ngayPhucVu, monAn.getHinhAnh()};
            model.addRow(rowData);
        }
    }

    private void initCombobox() {
        List<String> danhSachThucDon = thucDonDAO.layDanhSachTenThucDon();
        for (String tenThucDon : danhSachThucDon) {
            cbbThucDon.addItem(tenThucDon);
        }

        List<String> danhSachLoaiMon = thucDonDAO.layDanhSachLoaiMon();
        for (String loaiMon : danhSachLoaiMon) {
            cbbLoaiMon.addItem(loaiMon);
        }
    }

    private void clearTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblThucDon.getModel();
        dtm.setRowCount(0); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbThucDon = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblTenMon = new javax.swing.JTextField();
        lblHinh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbLoaiMon = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        chk246 = new javax.swing.JCheckBox();
        chk357 = new javax.swing.JCheckBox();
        btnLuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThucDon = new javax.swing.JTable();
        btnTim = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý thực đơn");

        jLabel2.setText("Thực Đơn");

        cbbThucDon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbThucDonItemStateChanged(evt);
            }
        });

        jLabel3.setText("Tên món:");

        jLabel5.setText("Loại món");

        cbbLoaiMon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiMonItemStateChanged(evt);
            }
        });

        jLabel6.setText("Ngày phục vụ:");

        buttonGroup1.add(chk246);
        chk246.setText("2,4,6,CN");
        chk246.setToolTipText("TD246");
        chk246.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk246ActionPerformed(evt);
            }
        });

        buttonGroup1.add(chk357);
        chk357.setText("3,5,7");
        chk357.setToolTipText("TD357");

        btnLuu.setBackground(new java.awt.Color(255, 51, 102));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        tblThucDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên món", "Loại món", "Ngày phục vụ", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThucDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThucDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThucDon);

        btnTim.setBackground(new java.awt.Color(255, 51, 102));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(255, 51, 102));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLuu)
                                    .addComponent(cbbLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chk246)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk357)))
                                .addGap(205, 205, 205))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTim)
                                .addGap(142, 142, 142)
                                .addComponent(btnMoi)
                                .addGap(103, 103, 103)))))
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lblTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbbLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(chk246)
                            .addComponent(chk357))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuu)
                            .addComponent(btnTim)
                            .addComponent(btnMoi))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbThucDonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbThucDonItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThucDonItemStateChanged

    private void chk246ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk246ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk246ActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String tenMon = lblTenMon.getText();
        String maThucDon246 = "1";
        String maThucDon357 = "2";

        if (chk246.isSelected()) {
            thucDonDAO.xoaMonAnKhoiThucDon(maThucDon246, tenMon);
            thucDonDAO.xoaMonAnKhoiThucDon(maThucDon357, tenMon);
            thucDonDAO.themMonAnVaoThucDon(maThucDon246, tenMon);
        } else if (chk357.isSelected()) {
            thucDonDAO.xoaMonAnKhoiThucDon(maThucDon246, tenMon);
            thucDonDAO.xoaMonAnKhoiThucDon(maThucDon357, tenMon);
            thucDonDAO.themMonAnVaoThucDon(maThucDon357, tenMon);
        }
        loadDanhSachMonAn();
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tblThucDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThucDonMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblThucDon.getSelectedRow();
        if (selectedRow >= 0) {
            String tenMonAn = tblThucDon.getValueAt(selectedRow, 0).toString();
            String loaiMonAn = tblThucDon.getValueAt(selectedRow, 1).toString();
            String hinh = tblThucDon.getValueAt(selectedRow, 3).toString();
            String ngayPhucVu = tblThucDon.getValueAt(selectedRow, 2).toString();

            cbbThucDon.setSelectedItem(ngayPhucVu);
            cbbLoaiMon.setSelectedItem(loaiMonAn);
            lblTenMon.setText(tenMonAn);
            String imagePath = "/Image/menu/" + hinh;
            InputStream inputStream = getClass().getResourceAsStream(imagePath);
            if (inputStream != null) {
                try {
                    BufferedImage originalImage = ImageIO.read(inputStream);

                    int scaledWidth = 150;
                    int scaledHeight = (int) (((double) scaledWidth / originalImage.getWidth()) * originalImage.getHeight());

                    Image scaledImage = originalImage.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);
                    ImageIcon scaledIcon = new ImageIcon(scaledImage);

                    lblHinh.setIcon(scaledIcon);

                    chk246.setSelected(ngayPhucVu.equals("Thứ 2,4,6,CN"));
                    chk357.setSelected(ngayPhucVu.equals("Thứ 3,5,7"));

                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            } else {
                System.err.println("Không thể tìm thấy hình ảnh: " + imagePath);
            }
        }
    }//GEN-LAST:event_tblThucDonMouseClicked

    private void cbbLoaiMonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiMonItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiMonItemStateChanged

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String keyword = JOptionPane.showInputDialog(this, "Nhập tên món ăn hoặc loại món ăn:", "Tìm kiếm sản phẩm", JOptionPane.QUESTION_MESSAGE);
        if (keyword == null || keyword.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa tìm kiếm.");
            return;
        }
        loadDanhSachMonAn();
        clearTable();
        ThucDonDAO tdDAO = new ThucDonDAO();
        List<Model.MonAn> thucDonList = tdDAO.layDanhSachThucDon();
        List<Model.MonAn> filteredList = new ArrayList<>();
        for (Model.MonAn sanPham : thucDonList) {
            if (sanPham.getTenMonAn().toLowerCase().contains(keyword.toLowerCase())
                    || sanPham.getLoaiMonAn().contains(keyword)) {
                filteredList.add(sanPham);
            }
        }
        int size = filteredList.size();
        if (size == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả nào!");
        } else {
            JOptionPane.showMessageDialog(this, "Tìm thấy " + size + " kết quả!");
        }
        loadDanhSachMonLenTable(filteredList);
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        loadDanhSachMonAn();
    }//GEN-LAST:event_btnMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLoaiMon;
    private javax.swing.JComboBox<String> cbbThucDon;
    private javax.swing.JCheckBox chk246;
    private javax.swing.JCheckBox chk357;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JTextField lblTenMon;
    private javax.swing.JTable tblThucDon;
    // End of variables declaration//GEN-END:variables
}
